# Generated by Django 3.0.8 on 2021-02-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='events_pics'),
        ),
    ]
